<?php


namespace api\modules\v1\controllers;


use yii\filters\ContentNegotiator;
use yii\rest\ActiveController;
use yii\rest\Serializer;
use yii\web\Response;

class BaseApiController extends ActiveController
{
    public $serializer = [
        'class'              => Serializer::class,
        'collectionEnvelope' => 'items'
    ];

    public function checkAccess($action, $model = null, $params = [])
    {
        //parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
        return true;
    }

    public function behaviors() {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::class,
                'formatParam' => '_format',
                'formats' => [
                    'json' => Response::FORMAT_JSON,
                    'xml' => Response::FORMAT_XML,
                ],
            ],

        ];
    }
}